
labels: ["Non-English"]
body:

  - type: input
    id: version
    attributes:
      label: "お使いのKH Coderのバージョン"
      description: "KH Coderのメニューから「ヘルプ」「KH Coderについて」を選択してバージョンをご確認ください。「3」だけでなく必ず「3.00 official-package」「3.Beta.08」のように正確に記入してください。"
      placeholder: "記入例：3.Beta.08, 3.00 official-package など。"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "内容をご自由にお書きください"
    validations:
      required: true

