
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        # Before posting questions.
        This Discussions board is a place for users to help each other. The more clearly and in detail you can describe what you are having question with, the more likely you are to receive a helpful response.
        
        When the question is solved, please mark the helpful comment as \"answer\". Also, it is good manners to make comments such as \"This operation solved it\" or \"This document helped me understand\".
        
        # References
        
        Your issue may be resolved by referring to the following materials.
        
        * [Tutorial slides](https://khcoder.net/en/tutorial_slides.pdf) and [video](https://www.youtube.com/watch?v=ULhddsc2Nqo)
        * Detailed tutorial: [Part I](http://www.ritsumei.ac.jp/file.jsp?id=325881) & [Part II](http://www.ritsumei.ac.jp/file.jsp?id=346128)
        * [manual](https://khcoder.net/en/manual_en_v3.pdf)
        
        # Describe your question in detail below

  - type: input
    id: version
    attributes:
      label: "Version number of KH Coder"
      description: "To check the version number, go to \"Help\" \"About\" in the menu of KH Coder. Please be sure to enter it correctly, such as \"3.Beta.07f\", not just \"3\"."
      placeholder: "e.g. 3.Beta.06, 2.00f, etc."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "Your Qeuestion"
      value: |
        **Your Operating System**
        ex. Windows 10, Mac OS X 10.12, Ubuntu 10.14, etc.
        
        **Your Qeuestion**
        A clear and concise description of your question.
        
        **Screenshots**
        If applicable, add screenshots to help explain your question.
        
        **What language of text are you trying to analyze?**
        ex. English, Japanese, Chinese, etc.
    validations:
      required: true

